# Matrix and Vector Operations 

In [1]:
# import numpy
import numpy as np

## `np.dot`

**Matrix multiplication (dot product) between two given arrays representing vectors, arrays, or tensors.**

In [20]:
# consider two 2D arrays 
A = np.arange(1, 7).reshape(2, 3)
print(f"Array A : \n {A}")

B = np.arange(1, 7).reshape(3, 2)
print(f"Array B : \n {B}")

Array A : 
 [[1 2 3]
 [4 5 6]]
Array B : 
 [[1 2]
 [3 4]
 [5 6]]


In [5]:
# Matrix Multiplication 
print(f"A x B = \n{np.dot(A,B)}")

print(f"B x A = \n{np.dot(B,A)}")

A x B = 
[[22 28]
 [49 64]]
B x A = 
[[ 9 12 15]
 [19 26 33]
 [29 40 51]]


In [25]:
# Instead if I take a one dimensional array we get a dot product
A = np.arange(1, 7)
B = np.arange(5, 11)

# Dot product
print(f"A.B = {np.dot(A,B)}")

# np.inner does the same 
print(f"A.B = {np.inner(A,B)}")

A.B = 175
A.B = 175


In [21]:
# A Matrix times a vector 
A = np.arange(1, 13).reshape(4, 3)
print(f"Array A : \n {A}")

B = np.arange(1, 4)[: , np.newaxis]
print(f"Array B : \n {B}")

print(f"A x B = \n{np.dot(A, B)}")

Array A : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Array B : 
 [[1]
 [2]
 [3]]
A x B = 
[[14]
 [32]
 [50]
 [68]]


In [24]:
# Let us now consider vectors 
A = np.arange(1, 7)[np.newaxis,:]
B = np.arange(5, 11)[:, np.newaxis]

# Thus A is a (1x6) matrix and B is a (6x1) matrix

# B x A gives a (6x6) matrix 
print(f"B x A = \n{np.dot(B,A)}")

# Dot Product as a (1X1) matrix i.e 2D array
print(f"A.B = {np.dot(A,B)}")


B x A = 
[[ 5 10 15 20 25 30]
 [ 6 12 18 24 30 36]
 [ 7 14 21 28 35 42]
 [ 8 16 24 32 40 48]
 [ 9 18 27 36 45 54]
 [10 20 30 40 50 60]]
A.B = [[175]]


In [29]:
# a 2D and a 1D array dot product

A = np.arange(1, 7).reshape(2, 3)
print(f"Array A : \n {A}")

B = np.arange(1, 4)
print(f"Array B : \n {B}")

# dot product between A and B
print(f"Dot product between A and B is :\n{np.dot(A,B)}")

Array A : 
 [[1 2 3]
 [4 5 6]]
Array B : 
 [1 2 3]
Dot product between A and B is :
[14 32]


Let us now calculate $Ap = BAB^{-1}$

In [26]:
A = np.random.rand(3,3)
B = np.random.rand(3,3)
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))

print(Ap)

[[-0.47586182  0.07716462  2.51127248]
 [-0.09928335  0.00338948  1.11863795]
 [-0.03554576  0.20164796  1.70533815]]
