# Create a layer of Neuron

In [9]:
class Neuron:
    def __init__(self, weights: list, bias: float) -> None:
        """
        Initialize the neuron with weights and a bias.
        :param weights: List of weights for each input.
        :param bias: The bias term for the neuron.
        """
        self.weights = weights 
        self.bias = bias 
    
    def output(self, inputs) -> float:
        """
        Calculate the output of the neuron using the formula:
        output = sum(inputs[i] * weights[i]) + bias
        :param inputs: List of input values.
        :return: The raw output of the neuron.
        """
        # Weighted sum calculation
        return sum(w * i for w,i in zip(self.weights, inputs)) + self.bias

class Layer:
    def __init__(self, neurons):
        """
        Initialize a layer with multiple neurons.
        :param neurons: List of Neuron objects.
        """
        self.neurons = neurons 
    
    def outputs(self, inputs):
        """
        Calculate the outputs of all neurons in the layer.
        :param inputs: List of input values.
        :return: List of outputs from all neurons.
        """
        return [round(neuron.output(inputs),2) for neuron in self.neurons]

In [10]:
# Example usage:
# Initialize weights and biases for 3 neurons
neuron1 = Neuron(weights=[0.2, 0.8, -0.5, 1.0], bias=2.0)
neuron2 = Neuron(weights=[0.5, -0.91, 0.26, -0.5], bias=3.0)
neuron3 = Neuron(weights=[-0.26, -0.27, 0.17, 0.87], bias=0.5)

# Create a layer with these neurons
layer = Layer(neurons=[neuron1, neuron2, neuron3])

# Example input for the layer (4 inputs)
inputs = [1, 2, 3, 2.5]

# Get the outputs of the layer
outputs = layer.outputs(inputs)
print(f"Layer outputs: {outputs}")

Layer outputs: [4.8, 1.21, 2.38]


# Create a Layer using NumPy
 

In [30]:
import numpy as np
class Neuron:
    def __init__(self, weights: "np.array", bias: float) -> None:
        """
        Initialize the neuron with weights and a bias.
        :param weights: NumPy array of weights for each input.
        :param bias: The bias term for the neuron.
        """
        self.weights = weights 
        self.bias = bias 
    
    def output(self, inputs: "np.array") -> float:
        """
        Calculate the output of the neuron using the formula:
        output = sum(inputs[i] * weights[i]) + bias
        :param inputs: NumPy array of input values.
        :return: The raw output of the neuron.
        """
        # Weighted sum calculation
        return np.dot(inputs, self.weights) + self.bias

class Layer:
    def __init__(self, neurons):
        """
        Initialize a layer with multiple neurons.
        :param neurons: List of Neuron objects.
        """
        self.neurons = neurons 
    
    def outputs(self, inputs):
        """
        Calculate the outputs of all neurons in the layer.
        :param inputs: List of input values.
        :return: List of outputs from all neurons.
        """
        return np.array([neuron.output(inputs) for neuron in self.neurons])

In [27]:
# Example usage:
# Initialize weights and biases for 3 neurons
neuron1 = Neuron(weights=[0.2, 0.8, -0.5, 1.0], bias=2.0)
neuron2 = Neuron(weights=[0.5, -0.91, 0.26, -0.5], bias=3.0)
neuron3 = Neuron(weights=[-0.26, -0.27, 0.17, 0.87], bias=0.5)

# Create a layer with these neurons
layer = Layer(neurons=[neuron1, neuron2, neuron3])

# Example input for the layer (4 inputs)
inputs = [1, 2, 3, 2.5]

# Get the outputs of the layer
outputs = layer.outputs(inputs)
print(f"Layer outputs: {outputs}")

Layer outputs: [4.8   1.21  2.385]


In [28]:
# Manual implementation

# describe the inputs 
inputs = np.array([1.0 , 2.0 , 3.0 , 2.5 ])

# describe the neurons i.e. the weights and the biases
weights = np.array([[ 0.2 , 0.8 , - 0.5 , 1 ],
                    [ 0.5 , - 0.91 , 0.26 , - 0.5 ],
                    [ - 0.26 , - 0.27 , 0.17 , 0.87 ]])
biases = np.array([ 2.0 , 3.0 , 0.5 ])

# output 
layer_outputs = np.dot(weights, inputs) + biases
print (layer_outputs)

[4.8   1.21  2.385]


## Batch of Data

In [19]:
import numpy as np

class Neuron:
    def __init__(self, weights, bias):
        """
        Initialize a neuron with weights and a bias.
        :param weights: List of weights for each input.
        :param bias: The bias term for the neuron.
        """
        self.weights = np.array(weights)
        self.bias = bias

    def output(self, inputs):
        """
        Calculate the output of the neuron for a batch of inputs.
        :param inputs: 2D NumPy array where each row is a set of inputs.
        :return: 1D NumPy array of outputs for the batch.
        """
        # Compute dot product for the batch and add the bias
        # The order of the dot product matters now - since here Broadcasting rules apply!
        return np.dot(inputs, self.weights) + self.bias


class Layer:
    def __init__(self, neurons):
        """
        Initialize a layer with multiple neurons.
        :param neurons: List of Neuron objects.
        """
        self.neurons = neurons

    def outputs(self, inputs):
        """
        Calculate the outputs of all neurons in the layer for a batch of inputs.
        :param inputs: 2D NumPy array where each row is a set of inputs.
        :return: 2D NumPy array where each row contains outputs for one input set.
        """
        # Compute the outputs for all neurons and stack them into a 2D array
        # Note the transpose we have to make
        return np.array([neuron.output(inputs) for neuron in self.neurons]).T


# Example usage:
# Define weights and biases for 3 neurons, each accepting 4 inputs
neuron1 = Neuron(weights=[0.2, 0.8, -0.5, 1.0], bias=2.0)
neuron2 = Neuron(weights=[0.5, -0.91, 0.26, -0.5], bias=3.0)
neuron3 = Neuron(weights=[-0.26, -0.27, 0.17, 0.87], bias=0.5)

# Create a layer with the 3 neurons
layer = Layer(neurons=[neuron1, neuron2, neuron3])

# Example batch of inputs (2D NumPy array)
inputs = np.array([
    [1, 2, 3, 2.5],  # First input set
    [2, 5, -1, 2],   # Second input set
    [-1.5, 2.7, 3.3, -0.8]  # Third input set
])

# Get the outputs of the layer for the batch
outputs = layer.outputs(inputs)
print(f"Layer outputs:\n{outputs}")


Layer outputs:
[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Here in the resultant output matrix, each row represent the output of a neuron of the layer!